//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluentDesign_Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Müsteriler
    {
        public int müsteri_id { get; set; }
        public string müsteri_adi { get; set; }
        public string müsteri_soyadi { get; set; }
        public string müsterinin_hesabi { get; set; }
        public string firma_adi { get; set; }
        public string vergi_no { get; set; }
        public string Teslimat_adresi { get; set; }
        public string tel_no { get; set; }
        public Nullable<bool> müsteri_onay { get; set; }
    }
}
